### ISSUE TITLE
Countdown Timer

### ISSUE THREAD

**Issue by lcorndogl** [lcorndogl/Hackathon-1-HTML-CSS-JavaScript#8]
**User Story**:
Have a timer to count down from a certain duration - countdown style

**Acceptance Criteria:**
- [ ] Timer starts counting down from 30s 
- [ ] Countdown audio plays in the final few seconds

**Tasks:**
- [ ] Make the timer start counting down when the user first starts the game
- [ ] Make the countdown audio start playing when the timer hits 5 seconds
- [ ] Make the game end so no more user inputs are accepted after the timer hits 0
